name: Docker Build

on:
    push:
      branches: [ master, docker-build ]

jobs:
    build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Load environment variables
              run: |
                echo "USER_UID=gs-user" >> $GITHUB_ENV
                echo "USER_GID=gs-user" >> $GITHUB_ENV
                echo "USERNAME=gs-used" >> $GITHUB_ENV
                echo "CUDA_VERSION=12.8.1" >> $GITHUB_ENV


            - name: Build Docker image
              run: docker build -t gaussian-splatting-cuda -f docker/Dockerfile .

            - name: Login to Docker Hub
              run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

            - name: Push Docker image to Docker Hub with tag
              run: docker push gaussian-splatting-cuda:${{ env.CUDA_VERSION }}-ubuntu24.04